-- Kiểm tra cấu trúc bảng CouponUsage
USE SP25_Demo;

-- Xem cấu trúc bảng CouponUsage
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'CouponUsage'
ORDER BY ORDINAL_POSITION;

-- Xem cấu trúc bảng Coupon
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Coupon'
ORDER BY ORDINAL_POSITION;